apiVersion: v1
kind: Service
metadata:
  labels:
    app: product_service
    tag: v1.0.0
  name: product_service
  namespace: { { .Values.namespace.name } }
spec:
  ports:
    - port: { { .Values.service.port } }
      protocol: TCP
      targetPort: { { .Values.service.port } }
  selector:
    app: product_service
    tag: v1.0.0
  type: { { .Values.service.type } }
