apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer_service
    tag: v1.0.0
  name: customer_service
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: customer_service
    tag: v1.0.0
  type: {{ .Values.service.type }} 
