apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer_service
    tag: v1.0.0
  name: customer-service
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: customer_service
      tag: v1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer_service
        tag: v1.0.0
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: customer_service
        resources:
{{ toYaml .Values.resources | indent 12 }}
